# Generated by Django 2.2.1 on 2019-05-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20190512_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(default=1, help_text='Função na empresa', max_length=100),
            preserve_default=False,
        ),
    ]
