# Generated by Django 2.2.1 on 2019-06-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_auto_20190528_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamentos',
            field=models.ManyToManyField(related_name='funcionario', to='departamentos.Departamento'),
        ),
    ]
