# Generated by Django 2.2.1 on 2019-06-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_auto_20190615_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ultimonome',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
