# Generated by Django 2.2.1 on 2019-06-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_auto_20190615_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil'),
        ),
    ]
