# Generated by Django 2.2.1 on 2019-06-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_remove_funcionario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='image',
            field=models.ImageField(default=1, upload_to='img_perfil'),
            preserve_default=False,
        ),
    ]
