# Generated by Django 2.2.1 on 2019-06-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_funcionario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='image',
            field=models.ImageField(upload_to='img_perfil/%Y/%m/%D/'),
        ),
    ]
