# Generated by Django 2.2.1 on 2019-06-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0014_auto_20190619_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil/%Y/%m/%D/'),
        ),
    ]
