# Generated by Django 2.2.1 on 2019-06-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0016_auto_20190619_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='image',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil/jpg'),
        ),
    ]
