# Generated by Django 2.2.1 on 2019-06-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0019_auto_20190619_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
