# Generated by Django 2.2.1 on 2019-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0022_auto_20190619_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(max_length=100, verbose_name='Função'),
        ),
    ]
