# Generated by Django 2.2.1 on 2019-06-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0024_auto_20190623_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='dat_modified',
            new_name='data_modified',
        ),
    ]
