# Generated by Django 2.2.1 on 2019-06-23 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0026_auto_20190623_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_modified',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
