# Generated by Django 2.2.1 on 2019-06-24 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0029_auto_20190623_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data cadastro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/perfil', verbose_name='Foto de perfil'),
        ),
    ]
