# Generated by Django 2.2.1 on 2019-06-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas_extras', '0003_auto_20190623_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='observacao',
            field=models.TextField(default=1, max_length=500, verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
