# Generated by Django 2.2.1 on 2019-06-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas_extras', '0004_registrohoraextra_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoraextra',
            name='time_he',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora atual'),
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='time_he1',
            field=models.DurationField(blank=True, null=True, verbose_name='Tempo total'),
        ),
    ]
