# Generated by Django 2.2.1 on 2019-06-27 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas_extras', '0009_auto_20190626_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohoraextra',
            name='time_he1',
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='date_time_final',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data e Hora Final'),
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='date_time_inicial',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data e Hora Inicial'),
        ),
    ]
