# Generated by Django 2.2.1 on 2019-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descricao',
            field=models.CharField(default=1, help_text='Descrição do departamento', max_length=200),
            preserve_default=False,
        ),
    ]
