# Generated by Django 2.2.1 on 2019-06-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
