# Generated by Django 2.2.1 on 2019-06-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='nome',
        ),
        migrations.AddField(
            model_name='documento',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
