# Generated by Django 2.2.1 on 2019-06-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_auto_20190617_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
